apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-test-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend-test-chart.name" . }}
      chart: {{ include "frontend-test-chart.chart" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "frontend-test-chart.name" . }}
        chart: {{ include "frontend-test-chart.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 3000

