apiVersion: apps/v1
kind: Deployment
metadata:
  name: rvms-backend-test
  namespace: {{ .Values.namespace }}
  labels:
    app: rvms-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rvms-backend-test
  template:
    metadata:
      labels:
        app: rvms-backend-test
    spec:
      containers:
        - name: rvms-backend-test
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
