apiVersion: v1
kind: Service
metadata:
  name: rvms-backend-test
  namespace: {{ .Values.namespace }}
  labels:
    app: rvms-backend-test
spec:
  ports:
    - name: http
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: rvms-backend-test
  type: {{ .Values.service.type }}
  externalIPs:
    - {{ .Values.service.externalIP }}
